apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-slave
  namespace: ansible-cluster
spec:
  replicas: 3  # Create 3 nodes for ansible testing
  selector:
    matchLabels:
      app: ansible-slave
  template:
    metadata:
      labels:
        app: ansible-slave
    spec:
      containers:
      - name: ansible-slave
        image: priyam930/ansible-slave
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-slave-svc
  namespace: ansible-cluster
spec:
  selector:
    app: ansible-slave
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
